import React from "react";
import {FreeTextFacet, ListFacet, SliderFacet, FacetsParams} from '@knaw-huc/browser-base-react';
import {FACET_URL} from "../misc/config";

export default function Facets({registerFacet, unregisterFacet, setFacet, searchValues}: FacetsParams) {
    return <>
        <FreeTextFacet registerFacet={registerFacet} unregisterFacet={unregisterFacet} setFacet={setFacet}/>
        <ListFacet registerFacet={registerFacet}
                   unregisterFacet={unregisterFacet}
                   setFacet={setFacet}
                   name="Sport"
                   field="sports.sport"
                   url={FACET_URL}
                   flex={false}
                   usePost={true}
                   searchValues={searchValues}/>
        <ListFacet registerFacet={registerFacet}
                   unregisterFacet={unregisterFacet}
                   setFacet={setFacet}
                   name="Naam"
                   field="naam"
                   url={FACET_URL}
                   flex={false}
                   usePost={true}
                   addFilter={true}
                   searchValues={searchValues}/>
        <ListFacet registerFacet={registerFacet}
                   unregisterFacet={unregisterFacet}
                   setFacet={setFacet}
                   name="Type"
                   field="type"
                   url={FACET_URL}
                   flex={false}
                   usePost={true}
                   searchValues={searchValues}/>
        <ListFacet registerFacet={registerFacet}
                   unregisterFacet={unregisterFacet}
                   setFacet={setFacet}
                   name="Plaats"
                   field="plaats"
                   url={FACET_URL}
                   flex={false}
                   usePost={true}
                   addFilter={true}
                   searchValues={searchValues}/>
        <ListFacet registerFacet={registerFacet}
                   unregisterFacet={unregisterFacet}
                   setFacet={setFacet}
                   name="Provincie"
                   field="provincie.provincie"
                   url={FACET_URL}
                   flex={false}
                   usePost={true}
                   searchValues={searchValues}/>
        <ListFacet registerFacet={registerFacet}
                   unregisterFacet={unregisterFacet}
                   setFacet={setFacet}
                   name="Landelijke bond"
                   field="landelijk.naam"
                   url={FACET_URL}
                   flex={false}
                   usePost={true}
                   addFilter={true}
                   searchValues={searchValues}/>
        <ListFacet registerFacet={registerFacet}
                   unregisterFacet={unregisterFacet}
                   setFacet={setFacet}
                   name="Regionale bond"
                   field="lokaal.naam"
                   url={FACET_URL}
                   flex={false}
                   usePost={true}
                   addFilter={true}
                   searchValues={searchValues}/>
        <SliderFacet
                    registerFacet={registerFacet}
                    unregisterFacet={unregisterFacet}
                    setFacet={setFacet}
                    name="Beginjaar"
                    field="beginjaar"
                    min={1900}
                    max={1940}/>
        <ListFacet registerFacet={registerFacet}
                   unregisterFacet={unregisterFacet}
                   setFacet={setFacet}
                   name="Status beginjaar"
                   field="begindatum_soort"
                   url={FACET_URL}
                   flex={false}
                   usePost={true}
                   addFilter={false}
                   searchValues={searchValues}/>
        <SliderFacet
            registerFacet={registerFacet}
            unregisterFacet={unregisterFacet}
            setFacet={setFacet}
            name="Eindjaar"
            field="eindjaar"
            min={1900}
            max={1940}/>
        <ListFacet registerFacet={registerFacet}
                   unregisterFacet={unregisterFacet}
                   setFacet={setFacet}
                   name="Status eindjaar"
                   field="einddatum_soort"
                   url={FACET_URL}
                   flex={false}
                   usePost={true}
                   addFilter={false}
                   searchValues={searchValues}/>
        <ListFacet registerFacet={registerFacet}
                   unregisterFacet={unregisterFacet}
                   setFacet={setFacet}
                   name="Levensbeschouwing"
                   field="levensbeschouwing"
                   url={FACET_URL}
                   flex={false}
                   usePost={true}
                   searchValues={searchValues}/>
    </>;
}
