version: '2'

services:
  sport-elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: sportelastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - sport_es:/usr/share/elasticsearch/data
    networks:
      - traefik-public

  sport-db:
    image: postgres:13
    container_name: sport-db
    restart: always
    volumes:
      - sport_db:/var/lib/postgresql/data
      - /home/robz:/home
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB: sport
    networks:
      - traefik-public


  sport-app:
    image: registry.diginfra.net/tsd/open-huygens-sport:0.9.1
    container_name: sport-app
    environment:
      ES_URI: sport-elastic
      SPORT_SERVER: sport-db
      POSTGRES_USER:
      POSTGRES_PASSWORD: 
      POSTGRES_DB: sport
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.sport-app.loadbalancer.server.port=5000"
      - "traefik.http.routers.sport-app.entrypoints=http"
      - "traefik.http.routers.sport-app.rule=Host(`sportdb.sd.di.huc.knaw.nl`)"
    expose:
      - 5000
    networks:
      - traefik-public


networks:
  traefik-public:
    external: true

volumes:
  sport_es:
    external: true
  sport_db:
    external: true




